# Generated by Django 6.0.1 on 2026-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
