# Generated by Django 6.0.1 on 2026-03-04 12:19

import homeworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_files/', validators=[homeworks.models.validate_file_size_7mb])),
                ('deadline', models.DateTimeField()),
                ('max_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DEADLINE', 'Deadline ogohlantirish'), ('NEW_HW', 'Yangi vazifa'), ('GRADED', 'Baholandi'), ('SYSTEM', 'Tizim xabari')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', validators=[homeworks.models.validate_file_size_5mb])),
                ('is_code', models.BooleanField(default=False, verbose_name='Kod sifatida topshirilgan')),
                ('code_language', models.CharField(blank=True, default='python', max_length=50)),
                ('score_percent', models.IntegerField(default=0)),
                ('is_graded', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('coin_rewarded', models.BooleanField(default=False)),
                ('coin_amount_awarded', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
