# Generated by Django 6.0.1 on 2026-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
