# Generated by Django 6.0.1 on 2026-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_alter_homework_created_at_alter_homework_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
