# Generated by Django 6.0.1 on 2026-04-11 06:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[core.validators.validate_file_10mb, core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='marketproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='marketproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_products/', validators=[core.validators.validate_file_10mb, core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='marketpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
