# Generated by Django 6.0.1 on 2026-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['sequence', 'created_at']},
        ),
        migrations.AddField(
            model_name='homework',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
