# Generated by Django 6.0.1 on 2026-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_alter_homework_options_alter_homework_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='coin_rewarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
