# Generated by Django 6.0.1 on 2026-02-06 04:53

import homeworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_submission_code_language_submission_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/', validators=[homeworks.models.validate_file_size_7mb]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[homeworks.models.validate_file_size_5mb]),
        ),
    ]
