name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/webdevaj/joylinks_Hoowork
            git fetch origin main
            git reset --hard origin/main
            source .venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput --clear
            
            # Ensure ALLOWED_HOSTS is correct
            sed -i "s/ALLOWED_HOSTS=.*/ALLOWED_HOSTS=hoowork.joylinks.uz,www.hoowork.uz,95.182.119.84,localhost,127.0.0.1/" .env || echo "ALLOWED_HOSTS=hoowork.joylinks.uz,www.hoowork.uz,95.182.119.84,localhost,127.0.0.1" >> .env

            # Restart the service
            sudo systemctl restart joylinks
